sonar.projectKey=MiteshKumarEM_eventnest-devops-jenkins
sonar.organization=miteshkumarem
sonar.projectName=EventNest DevOps Pipeline
sonar.sources=src,public
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**,reports/**,data/**,public/styles.css
sonar.sourceEncoding=UTF-8
